services:
  frontend:
    build: ./flight-management-ui
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - DB1_URL=${DB1_URL}
      - CACHE_URL=${CACHE_URL}
    depends_on:
      - users_db
      - cache

  flight-service:
    build: ./flight-service
    ports:
      - "5001:5000"
    restart: unless-stopped
    environment:
      - DB2_URL=${DB2_URL}
      - CACHE_URL=${CACHE_URL}
    depends_on:
      - flights_db
      - cache

  users_db:
    image: postgres:18.1
    ports:
      - "27017:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB1}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - users_db_data:/var/lib/postgresql
      - ./init-docker-scripts/users_db:/docker-entrypoint-initdb.d

  flights_db:
    image: postgres:18.1
    ports:
      - "27018:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB2}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - flights_db_data:/var/lib/postgresql
      - ./init-docker-scripts/flights_db:/docker-entrypoint-initdb.d
  
  cache:
    image: redis:8.4
    ports:
      - "6379:6379"
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redisdata:/data

volumes:
  users_db_data:
  flights_db_data:
  redisdata: